// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnovnrisewzgtxmvorwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impub3ZucmlzZXd6Z3R4bXZvcndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODg2MTcsImV4cCI6MjA2NTU2NDYxN30.kPMV0fsLFv2_O0_SNqhK0m9CXkkhS4GnwZso9kyelnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);